services:
  - type: web
    name: inventory-backend
    env: docker
    plan: free
    branch: main

    # Path to Dockerfile from repo root (Projects/)
    dockerfilePath: Inventory Management System/Backend/Middle_layer(Java)/IMS/Dockerfile

    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
