services:
  - type: web
    name: inventory-backend
    env: docker
    plan: free
    branch: main

    # Path from repo root to your Dockerfile
    rootDir: InventoryManagementSystem/Backend/MiddleLayer/IMS

    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASS
        sync: false
