services:
  - type: web
    name: inventory-backend
    env: docker
    plan: free
    branch: main
    dockerfilePath: Backend/Middle_layer(Java)/IMS/Dockerfile
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
